---
title: "Sex Ed Classification"
subtitle: "Insert Subtitle"
author: 
  - Rosemarie Topp
thanks: "Code and data are available at: "
date: today
date-format: long
abstract: "Insert abstract"
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false
# loading libraries
library(knitr)
```

# Introduction

**Due to the subject matter, this paper contains sensitive language that may be considered offensive.**

The state of sexuality education in schools varies around the world. The topic of if, when, and how to introduce children to certain subjects is divisive, and often raises religious, political, and moral issues. According to the @citeWHO, comprehensive sexuality education is defined as "a curriculum‑based, incremental and scientifically-accurate approach that teaches children and young people about the cognitive, emotional, physical and social aspects of sexuality in a culturally-relevant and **age-appropriate** way." That being said, what is considered age-appropriate for a given demographic is hard to define. Even if it could be universally agreed upon that a piece of content was inappropriate for children to consume, the exact reasons why may be hard to put into words. The exact criteria often comes down to what United States Supreme Court Justice Potter Stewart once said when asked to define obscene pornography: "I know it when I see it" [@citeLattman].

According to a 2024 report, 66,000 Instagram posts, 347,200 Tweets, and 1.7 million Facebook posts were shared every minute of the year [@citeDomo]. Many of these pieces of content may contain sensitive themes. Websites such as Youtube or TikTok are frequented by  children seeking educational information [@citeDoring]. In the early 2000s, before censorship laws were put in place, the internet was essentially unregulated, allowing anyone with internet access to consume and post offensive, violent, and pornographic material. Over the years, various countries have put legislation in place to help hide sensitive content from younger users, such as Canada's recent Bill C-34, which mandates the implementation of safeguards on social media sites and AI chatbots in order to protect children from harmful material [@citeC34]. The detection of inappropriate content on websites frequented by minors has thus become a legal necessity, making research in the area of data classification of great interest to social media companies. Seeing as it is virtually impossible for humans to manually check content at this volume, Justice Stewart's criteria falls short in today's world.

Instead, companies perform this detection using a mix of algorithms and user reports. In 2021, Meta announced they would begin using artificial intelligence models trained with few-shot learning to detect harmful content on their platforms [@citeMeta]. Few-shot learning is a technique in which a model is provided with some small number of demonstrative examples before a task is given [@citeBrown]. This is a common method used to help improve the accuracy of LLM text classification. Text classification is an important area of natural language processing, a subfield of computer science that focuses on getting computers to work with human language. Traditional methods for representing text ignored semantic meaning, and would, for example, treat the word "tie" the same whether it referred to the accessory or an equal score [@citeAltinel]. Newer models have overcome this limitation and are able to not only discern between homonyms, but understand tonal differences in text that can be easily picked up on by humans but are very difficult to define. This has vastly broadened the use cases for artificial intelligence.

With the recent advances in semantic text classification technology, much research is being done attempting to use natural language processors as models for human behavior and attitudes. The training corpus for many leading LLMs is essentially the whole internet, containing every human thought ever published online. This creates an interesting opportunity to see how well model responses reflect human populations.

Insert paragraph about methods and results

This rest of this report will be separated into the following sections: @sec-background will provide background information on the key areas most relevant to this paper. @sec-data will showcase the data used in the analysis. @sec-methods will describe the methods used [say something else about the methods]. @sec-results will detail the results and findings of the analysis. @sec-discussion will discuss the big picture relevance of the results.

# Background {#sec-background}
The content of this paper involves three main subjects: (1) childhood sexuality education, (2) online censorship, and (3) semantic text classification. Much research has been done in all three areas that have greatly informed and inspired this report.

## Childhood Sexuality Education
Legislation regarding sex education varies greatly around the world, even within countries such as Canada and the United States. An extreme example of this is the United States, which is known for its great political divide. SEICUS, an organization dedicated to promoting healthy sexual education in the US, has created detailed state profiles that go in depth on each region's position on how sex ed should be delivered to students [@citeSEICUS]. As of 2025, 14 states provide abstinence-only education, which has been shown to fail in protecting students from sexually transmitted illness and pregnancy [@citeSantelli]. 19 states exclude and/or stigmatize LGBTQ+ people in their sex education. Only three states, California; Oregon and Washington, require comprehensive sexuality education in all schools.

Different areas have vastly different ideas of what is age-appropriate for those under the age of 18 to learn about. Parents and guardians may have a desire to shelter their children from certain subjects for fear that learning about sexuality and gender will increase risky behaviour, however there is much evidence to the contrary [@citeWHO]. A paper on parental attitudes towards the K-12 gender and sexuality curriculum in Australia identified that many believe children are too immature and easily influenced to learn about these topics [@citeFerfolja]. Regardless of age-appropriateness, young people may be exposed to sexual concepts through the internet, peers, and real life experiences. Without a reliable foundation of knowledge from which to draw from, they may be unable to tell myth from truth.

## Online Censorship and Age Restriction
As the internet and social media gain increasing popularity, countries have each put in place legislation to regulate what kind of content can be posted online. The Online Streaming Act (Bill C-11) of 2022 gave the Canadian Radio and Television Commission the ability to regulate Canadian digital media platforms the same way they had been regulating radio and TV broadcasters [@citeWoolf]. This bill received pushback from those who hold the opinion that online censorship infringes on human rights [@citeLewis]. Regardless, many social media platforms are getting increasingly strict with their terms of service due to financial and legal pressure, such as content platform OnlyFans banning sexually explicit content at the request of credit card companies [@citeCNN] [@citeLiao]. The Canadian government has stated that they intend to implement a social media ban for those under the age of 16, with an exemption for platforms that have sufficient safeguards in place [@citeC34]. These safeguards must protect children from viewing "harmful content", which is defined as media that falls into any of these categories:

  - Intimate content communicated without consent
  - Content that sexually victimizes a child or revictimizes a survivor
  - Content that induces a child to harm themselves
  - Content used to bully a child
  - Content that foments hatred
  - Content that incites violence
  - Terrorism or violent extremism content

Unfortunately many of these types of content cannot be fully accurately detected by a simple algorithm. There is no one word that is in every piece of hate speech, no single phrase that consistently promotes violence. Platforms often use user reports to aid algorithms in this detection, however this opens the door to unwarranted mass reporting performed by bots or spiteful users [@citeContreras]. Content by LGBTQ+ individuals is often disproportionately suppressed, and sexual education is usually detected as explicit [@citeTremblay] [@citeYork] [@citeZhang]. Additionally, many posts that arguably do fit the criteria go unremoved [@citeSeitz]. It would be impossible for a healthy sample of humans to go through every social media post and assess potential harm. It is in the best interest of companies to build more intelligent algorithms that are able to detect nuanced semantics in order to keep online spaces safe and inclusive.

## Text Classification
Text classification is a common task in machine learning in which a model has to assign a category or label to a piece of text. This category could be the topic the text is relating to, the sentiment, the tone, or something else entirely. There are many different techniques used to complete this task.

The majority of text classification performed today is supervised [@citeStryker]. In this method, sets of pre-classified text (which have been labeled by humans) are fed to the model in order to train it. The model uses these examples to get an idea of what goes in each category. It is then given new pieces of text which it must classify according to this same pattern.

Text clustering is a type of unsupervised text classification, a method where instead of training the model on labeled examples, it finds patterns within the data. This technique essentially puts texts into groups based on semantic similarity. Texts within the same cluster are assumed to relate to the same topic. After this is performed, the clusters can be inspected to determine which topic they each refer to.

Zero-shot, one-shot, and few-shot learning are all prompting techniques used to improve the ability of a pre-trained model to perform a specified task. The model is first given some number of completed examples of said task, and then asked to perform it on new data. Few-shot refers to multiple examples, one-shot refers to one, and zero-shot asks the model to execute the task based solely on what it already knows. In the context of text classification, this would look like simply prompting the model to classify some piece of text, usually into a specified set of categories. Zero-shot is often used when there is no labeled data available with which to provide examples. While this method has less accuracy than one- and few-shot learning, it still proves to be quite successful, with GPT-3 achieving 64.3% accuracy on TriviaQA, a dataset of question and answer problems, and 76% on LAMBADA, a dataset used to test word prediction capabilities [@citeBrown].

# Data {#sec-data}

## Overview

The data analyzed in this paper comes from the 2014 edition of the book *It's Perfectly Normal* by Robbie Harris and Michael Emberley. All handling of data was done using the statistical programming language R [@citeR] as well as Python version 3.13 [@citePython]. R package `readr` [@citeReadr], and Python packages `pdfminer` [@citePdfminer], `nltk` [@citeNltk], `re` [@citeRe], and `csv` [@citeCsv] were used to clean, analyze, and simulate data. R package `ellmer` [@citeEllmer] was used to access the models used in this analysis. All plots were created using `ggplot2` [@citeGgplot2]. `knitr` was used to help format this document [@citeKnitr].

## *It's Perfectly Normal*
The data used in this analysis is a random sample of sentences collected from the most recent edition of the book *It's Perfectly Normal* by Robbie Harris and Michael Emberley, published in 2014 [@citeHarris]. The first edition of this book was originally published in 1994 and has since been updated three times [@citeFlynn]. *It's Perfectly Normal* is a sexual education book intended for children ages 10 and up, and has been praised for its clear language, comprehensive information, and discussion of the LGBTQ+ community [@citePerring]. Despite this, the picture book has also gained widespread controversy for its detailed illustrations and themes which some consider to be inappropriate for the target audience [@citeHersher]. It has frequently topped the American Library Association's list of most challenged books since its original release over two decades ago [@citeALA].

## Cleaning
In order to use the text from *It's Perfectly Normal*, the book was parsed into individual sentences in Python [@citeHarris] [@citePython]. The package `pymupdf` was used to extract text from the pdf of the book [@citePymupdf]. The package `nltk` was then used to turn individual sentences into tokens which were then written into a csv file [@citeNltk]. This processed resulted in some "sentences" that contained no alphabetical letters, and these were removed. While much effort was taken to preserve the book's intended text format, there are a small number of row entries containing fragments of different sentences concatenated together.

# Methods {#sec-methods}
Several models were used to examine how generative LLMs classify text-based sexual education material. Default parameters were maintained on all models except for temperature. The temperature of a model indicates the variability of its responses, with 0 being the least variable and 1 the most. This parameter was set to 0.4 in order to examine how model response varies. The models used were Open AI's GPT 4o mini, GPT 5.4 mini, and GPT 4, Deepseek's V4 Flash, [add more models].

In order to prompt the models, zero-shot learning was employed. Zero-shot refers to a prompting style where no demonstrative examples are provided, and the model must base its answer on previous knowledge. 200 unique sentence excerpts from *It's Perfectly Normal* were provided to each model, in the following format: 'Is the following text in quotes appropriate for children ages 10 and up? Answer yes or no [sentence in quotations]'. Models then provide a yes or no response. Each text excerpt was provided to each model 50 times, and responses were recorded.



# Results {#sec-results}

# Discussion {#sec-discussion}

# References
